@startuml
top to bottom direction
skinparam backgroundColor white
skinparam actorStyle stickman
skinparam shadowing false
skinparam packageStyle rectangle

actor "Студент" as Student
actor "Преподаватель" as Teacher

rectangle "Система анализа документов" {
  usecase "Загрузить документ" as UC1
  usecase "Запустить анализ документа" as UC2
  usecase "Определить тип документа" as UC3
  usecase "Определить семестр документа" as UC4
  usecase "Проверить соответствие требованиям" as UC5
  usecase "Получить отчёт" as UC6

  UC1 -[hidden]down- UC2
  UC2 -[hidden]down- UC3
  UC3 -[hidden]down- UC4
  UC4 -[hidden]down- UC5
  UC5 -[hidden]down- UC6
}

Student -> UC1
Student -> UC2
Student -> UC6

Teacher -> UC2
Teacher -> UC6

UC2 .> UC3 : <<include>>
UC2 .> UC4 : <<include>>
UC2 .> UC5 : <<include>>

@enduml